# Generated by Django 3.2 on 2021-06-09 18:38

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Короткое наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('version', models.CharField(max_length=16, unique=True, verbose_name='Версия справочника')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата начала действия')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=64, verbose_name='Код элемента')),
                ('element_value', models.CharField(max_length=255, verbose_name='Значение элемента')),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='catalog.catalog', verbose_name='Родительский идентификатор')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'ordering': ['-catalog_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_version_catalog'),
        ),
    ]
