# Generated by Django 3.2 on 2021-06-11 12:48

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='version',
            field=models.CharField(max_length=16, unique=True, validators=[catalog.models.validate_version], verbose_name='Версия справочника'),
        ),
    ]
