# Generated by Django 3.2 on 2021-06-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['-name'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
    ]
