# Generated by Django 3.2 on 2021-06-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210611_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('catalog_id', 'element_code')},
        ),
    ]
