# Generated by Django 3.2 on 2021-06-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_catalog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='catalog.catalog', verbose_name='Справочник'),
        ),
    ]
