# Generated by Django 3.2 on 2021-06-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_element_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='catalog_id',
            new_name='catalog',
        ),
    ]
